language: php

git:
  depth: 1

php:
    - 5.6

install:
  - travis_retry composer install --no-interaction

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml

branches:
  only: master

notifications:
     email:
        on_success: never
        on_failure: always

cache:
  directories:
  - vendor
  - $HOME/.cache/composer