language: php

git:
  depth: 1

php:
    - 5.6

install:
  - travis_retry composer install --no-interaction

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml  --coverage-clover=coverage.xml

branches:
  only: master

notifications:
     email:
        on_success: never
        on_failure: always

cache:
  directories:
  - vendor
  - $HOME/.cache/composer

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 1cdcf762-abdb-4fd6-bf4c-aa3b3e3244de